// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX7vraLxeU-glYeMZ6MoGn5S0whhmretw',
    appId: '1:668104791199:web:5b808e9a30e021ae3f3eaa',
    messagingSenderId: '668104791199',
    projectId: 'nconapp-cbc22',
    authDomain: 'nconapp-cbc22.firebaseapp.com',
    storageBucket: 'nconapp-cbc22.firebasestorage.app',
    measurementId: 'G-YR66LVRXDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWK8hdUHyqtNEAp9PC0_0TSTmbyrevcdI',
    appId: '1:668104791199:android:eae5c315a816ccd43f3eaa',
    messagingSenderId: '668104791199',
    projectId: 'nconapp-cbc22',
    storageBucket: 'nconapp-cbc22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk-1M8xN1_Ute6wA5Ci0hs1ajEcUvnP7g',
    appId: '1:668104791199:ios:3fb31b9e508de93e3f3eaa',
    messagingSenderId: '668104791199',
    projectId: 'nconapp-cbc22',
    storageBucket: 'nconapp-cbc22.firebasestorage.app',
    iosBundleId: 'com.example.nconApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk-1M8xN1_Ute6wA5Ci0hs1ajEcUvnP7g',
    appId: '1:668104791199:ios:3fb31b9e508de93e3f3eaa',
    messagingSenderId: '668104791199',
    projectId: 'nconapp-cbc22',
    storageBucket: 'nconapp-cbc22.firebasestorage.app',
    iosBundleId: 'com.example.nconApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX7vraLxeU-glYeMZ6MoGn5S0whhmretw',
    appId: '1:668104791199:web:5159e1d462fd47763f3eaa',
    messagingSenderId: '668104791199',
    projectId: 'nconapp-cbc22',
    authDomain: 'nconapp-cbc22.firebaseapp.com',
    storageBucket: 'nconapp-cbc22.firebasestorage.app',
    measurementId: 'G-7W2E512KCV',
  );

}